/*
 * ******************************************************************************
 *   Copyright 2014-2015 Spectra Logic Corporation. All Rights Reserved.
 *   Licensed under the Apache License, Version 2.0 (the "License"). You may not use
 *   this file except in compliance with the License. A copy of the License is located at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 *   or in the "license" file accompanying this file.
 *   This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 *   CONDITIONS OF ANY KIND, either express or implied. See the License for the
 *   specific language governing permissions and limitations under the License.
 * ****************************************************************************
 */

package com.spectralogic.ds3autogen.utils.test.utils;

import com.google.common.collect.ImmutableList;
import com.google.common.collect.ImmutableMap;
import com.spectralogic.ds3autogen.api.models.*;

import static org.hamcrest.Matchers.is;
import static org.hamcrest.Matchers.nullValue;
import static org.junit.Assert.assertThat;

/**
 * This class provides utilities for testing the Response Type Converter utility
 */
public class ResponseTypeConverterHelper {

    private ResponseTypeConverterHelper() { }

    /**
     * Creates a populated list of Ds3ResponseTypes with the ability to set a variation to append
     * to type and component type names to ensure name uniqueness.
     */
    public static ImmutableList<Ds3ResponseType> createPopulatedDs3ResponseTypeList(final String variation) {
        return ImmutableList.of(
                new Ds3ResponseType("SimpleType" + variation, null),
                new Ds3ResponseType("array", "SimpleComponentType" + variation),
                new Ds3ResponseType("com.spectralogic.s3.common.dao.domain.tape.TapePartition" + variation, null),
                new Ds3ResponseType("array", "com.spectralogic.s3.common.dao.domain.ds3.BucketAcl" + variation));
    }

    /**
     * Creates a populated list of Ds3ResponseCodes
     */
    public static ImmutableList<Ds3ResponseCode> createPopulatedDs3ResponseCodeList(
            final String firstVariation,
            final String secondVariation) {
        return ImmutableList.of(
                new Ds3ResponseCode(
                        200,
                        createPopulatedDs3ResponseTypeList(firstVariation)),
                new Ds3ResponseCode(
                        205,
                        createPopulatedDs3ResponseTypeList(secondVariation)));
    }

    /**
     * Creates a populated Ds3Request. This request is empty except for having
     * a uniquely populated response code list which has unique response type names.
     * The unique names are created by appending the user supplied variations to
     * the template names.
     */
    public static Ds3Request createPopulatedDs3Request(
            final String firstVariation,
            final String secondVariation
    ) {
        return new Ds3Request(null, null, null, null, null, null, null, null, null,
                createPopulatedDs3ResponseCodeList(firstVariation, secondVariation), null, null);
    }

    /**
     * Creates a populated list of Ds3Requests. These requests are empty except for
     * having uniquely populated response code lists based on the user specified
     * variations to be added to the type names.
     */
    public static ImmutableList<Ds3Request> createPopulatedDs3RequestList(
            final String firstVariation,
            final String secondVariation,
            final String thirdVariation,
            final String fourthVariation
    ) {
        return ImmutableList.of(
                createPopulatedDs3Request(firstVariation, secondVariation),
                createPopulatedDs3Request(thirdVariation, fourthVariation));
    }

    /**
     * Creates a populated Ds3Type map which contains TapePartition and TapeDriveType keys,
     * but where the associated types are both empty
     */
    public static ImmutableMap<String, Ds3Type> createPopulatedDs3TypeMap() {
        return ImmutableMap.of(
                "com.spectralogic.s3.common.dao.domain.tape.TapePartition", new Ds3Type(null, null, null),
                "com.spectralogic.s3.common.dao.domain.tape.TapeDriveType", new Ds3Type(null, null, null));
    }

    /**
     * Verifies that a list of ResponseTypes that were generated by this utility have been
     * properly updated.
     * @param updatedResponseTypes The list of updated Response Types
     * @param originalResponseTypes The list of original Response Types that needed updating
     * @param variation The name variation used to auto populate unique Response Type names
     */
    public static void verifyPopulatedResponseTypeList(
            final ImmutableList<Ds3ResponseType> updatedResponseTypes,
            final ImmutableList<Ds3ResponseType> originalResponseTypes,
            final String variation) {
        assertThat(updatedResponseTypes.size(), is(4));
        assertThat(updatedResponseTypes.get(0), is(originalResponseTypes.get(0)));
        assertThat(updatedResponseTypes.get(2), is(originalResponseTypes.get(2)));

        assertThat(updatedResponseTypes.get(1).getType(),
                is("SimpleComponentType" + variation + "List"));
        assertThat(updatedResponseTypes.get(1).getComponentType(), is(nullValue()));
        assertThat(updatedResponseTypes.get(3).getType(),
                is("com.spectralogic.s3.common.dao.domain.ds3.BucketAcl" + variation + "List"));
        assertThat(updatedResponseTypes.get(3).getComponentType(), is(nullValue()));
    }
}
